# Generated by Django 2.1.7 on 2019-03-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20190327_1911'),
        ('core', '0002_auto_20190327_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='expense_category',
            field=models.ManyToManyField(to='finances.ExpensesCategory'),
        ),
    ]
